### PR TITLE
import normalize! from Compat if defined there

### PR DESCRIPTION
**Pull request by tkelman**
the latest tag of Compat.jl caused this package's tests to fail with
`both Compat and RouletteWheels export "normalize!"; uses of it in module Main must be qualified`

### CODE REVIEW

**Comment by jbn** [comment]
Thanks, @tkelman!

**Comment by tkelman** [comment]
No problem! You may want to tag this to get it green on PackageEvaluator.

**Comment by jbn** [comment]
The machine I am on doesn't have `Julia` and I don't remember exactly what `Pkg` did under the covers. But, once I return home at the end of this week, I'll do so. Thanks for the catch.

**Comment by tkelman** [comment]
No rush, but for your information what it does is create and push a git tag v0.0.6 from latest master, then add 2 files to METADATA.jl here: https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/RouletteWheels/versions
1. A `RouletteWheels/versions/0.0.6/requires` file that is a copy of the `REQUIRE` file here, and
2. A `RouletteWheels/versions/0.0.6/sha1` file that lists the git sha1 of the tagged commit

**Pull request merged**
